id = "mpls"
name = "MPLS"
version = "0.1.0"
schema_version = 1
authors = ["pnyda <135603985+pnyda@users.noreply.github.com>"]
description = "Zed extension for Markdown Preview Language Server"
repository = "https://github.com/pnyda/zed-mpls"

[language_servers.mpls]
name = "MPLS"
language = "Markdown"
